name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Use setup-node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - id: tagaction
        name: Use github-tag-action
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Bump NPM Project version
        run: npm version ${{ steps.tagaction.outputs.tag }}
