name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: 'Use checkout from actions'
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - id: tagaction
        name: 'Use github-tag-action from anothrNick'
        uses: anothrNick/github-tag-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
